import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Adeel's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div class="grid place-items-center h-screen">
        <h3 >HOME PAGE</h3>
        
      </div>
      
    </div>
  )
}
